
# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
# TODO: make Tess mult-thread
num_workers: 0

# Number of milliseconds to wait for a heartbeat from worker before killing
# and restarting it
worker_heartbeat_timeout: 7500

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
worker_heap_limit_mb: 500

# Logger info
logging:
  level: info
#  streams:
#  # Use gelf-stream -> logstash
#  - type: gelf
#    host: logstash1003.eqiad.wmnet
#    port: 12201

# Statsd metrics reporter
# metrics:
#   type: statsd
#   host: localhost
#   port: 8125

services:
  - name: tess
    module: app.js
    conf:
      port: 3000
  - name: tess-telegraf
    module: modules/telegraf/app.js
    conf:
      token: "TELEGRAM_TOKEN"
